### ISSUE TITLE
hello ~ I'm sorry to trouble you~

### ISSUE THREAD

**Issue by coutliuxing** [a-martynovich/SampleApp#1]
Hello, I see you have followed androvm project. Do you still have the source code of this project?? As there is no other contact information, can only leave a message in your project, sorry~

**Comment by a-martynovich** [comment]
@coutliuxing here's my fork of a part of it: https://github.com/a-martynovich/device_androVM. You can also contact Daniel Fages directly.

**Comment by coutliuxing** [comment]
It's empty. There's nothing in it.So I can only hope that you have saved it locally

**Comment by a-martynovich** [comment]
Please look at the other branches in this repo.
